Imports System.Windows.Forms

Friend Class AuthorizationForm

    Private Sub OK_Button_Click(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Me.DialogResult = System.Windows.Forms.DialogResult.OK
        Me.Close()




    End Sub

    Private Sub Cancel_Button_Click(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Me.DialogResult = System.Windows.Forms.DialogResult.Cancel
        Me.Close()
    End Sub

    Private Sub AuthorizationForm_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Label1.Text = "You are authorized to use this System for approved " & vbCrLf & " purposes only. Use for any other purpose is " & vbCrLf & "prohibited. All transactional records, reports, e-mail, " & vbCrLf & " software and other data generated by or residing upon " & vbCrLf & " this System are the property of the Company and may " & vbCrLf & " be used by the company for any purpose. Authorized" & vbCrLf & " and unauthorized activities may be monitored."
    End Sub

    Private Sub btn_accept_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn_accept.Click
        Me.Close()
    End Sub
End Class
